[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/Greyhold/*"
  to = "/Greyhold/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/Greyhold/"
  status = 301
  force = true